port: ":8888"
static_folder: "static/"
secret_key: "FO00XG0P0ndas1CrOkBos55JAYUDA44e4ateByVNEU@20200218Gara2BCA"
jwt_expired_time: 1
primary_db:
  host: "172.19.0.2"
  username: "root"
  password: "a"
  db_name: "CodeInterview"
  port: "3306"